# Generated by Django 4.2.9 on 2024-01-29 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_registration', models.CharField(max_length=30)),
                ('delivery_number', models.CharField(max_length=20)),
                ('loading_date', models.DateField()),
                ('fuel_gauge', models.CharField(choices=[('empty', 'Empty'), ('half', 'Half'), ('full', 'Full')], max_length=10)),
                ('water_reservoir', models.CharField(choices=[('empty', 'Empty'), ('half', 'Half'), ('full', 'Full')], max_length=10)),
                ('number_of_seals', models.IntegerField()),
                ('seals_condition', models.CharField(max_length=50)),
                ('sealing_condition', models.CharField(max_length=50)),
                ('seals_identification', models.TextField()),
                ('cleanliness', models.CharField(max_length=50)),
                ('leakages', models.BooleanField()),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('time_out', models.DateTimeField(auto_now=True)),
                ('officer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OffloadingBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_registration', models.CharField(max_length=30)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('time_out', models.DateTimeField()),
                ('notes', models.TextField()),
                ('operator_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeighBridgeOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_registration', models.CharField(max_length=30)),
                ('last_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_difference', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('operator_name', models.CharField(max_length=100)),
                ('officer_name', models.CharField(max_length=100)),
                ('offloading_bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weigh_bridge_outs', to='backend.offloadingbay')),
            ],
        ),
        migrations.CreateModel(
            name='WeighBridgeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_registration', models.CharField(max_length=30)),
                ('delivery_number', models.CharField(max_length=20)),
                ('first_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('time_out', models.DateTimeField()),
                ('operator_name', models.CharField(max_length=100)),
                ('officer_name', models.CharField(max_length=100)),
                ('gate_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weigh_bridge_ins', to='backend.gateentry')),
            ],
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_registration', models.CharField(max_length=30)),
                ('sample_type', models.CharField(choices=[('CPO', 'CPO'), ('CPKO', 'CPKO'), ('stearin', 'Stearin'), ('water', 'Water'), ('sludge', 'Sludge'), ('caustic', 'Caustic')], max_length=10)),
                ('sample_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField()),
                ('inspector_name', models.CharField(max_length=100)),
                ('sampling_time', models.DateTimeField(auto_now_add=True)),
                ('chemist_name', models.CharField(max_length=100)),
                ('sample_number', models.CharField(max_length=50)),
                ('result_time', models.DateTimeField(auto_now_add=True)),
                ('SMP', models.DecimalField(decimal_places=2, max_digits=5)),
                ('MIV', models.DecimalField(decimal_places=2, max_digits=5)),
                ('FFA', models.DecimalField(decimal_places=2, max_digits=5)),
                ('COLOR_B', models.IntegerField()),
                ('COLOR_Y', models.IntegerField()),
                ('COLOR_R', models.IntegerField()),
                ('IV', models.IntegerField()),
                ('result_out', models.DateTimeField(auto_now=True)),
                ('weigh_bridge_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_controls', to='backend.weighbridgein')),
            ],
        ),
        migrations.AddField(
            model_name='offloadingbay',
            name='quality_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offloading_bays', to='backend.qualitycontrol'),
        ),
    ]
