# Generated by Django 4.2.9 on 2024-01-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_gateentry_time_in_alter_gateentry_time_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycontrol',
            name='sampler_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
