# Generated by Django 4.2.9 on 2024-01-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_gateentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weighbridgein',
            options={'verbose_name': 'Weigh Bridge In'},
        ),
    ]
