# Generated by Django 4.2.9 on 2024-01-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_qualitycontrol_sampler_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='weigh_bridge_in',
        ),
    ]
