# Generated by Django 4.2.9 on 2024-01-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_qualitycontrol_weigh_bridge_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offloadingbay',
            name='quality_control',
        ),
        migrations.RemoveField(
            model_name='weighbridgein',
            name='gate_entry',
        ),
        migrations.RemoveField(
            model_name='weighbridgeout',
            name='offloading_bay',
        ),
    ]
