# Generated by Django 4.2.9 on 2024-01-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_offloadingbay_quality_control_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gateentry',
            options={'verbose_name': 'Gate Entry'},
        ),
    ]
