# Generated by Django 4.2.9 on 2024-01-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_weighbridgein_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gateentry',
            options={'verbose_name_plural': 'Gate Entries'},
        ),
    ]
