# Generated by Django 4.2.9 on 2024-01-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_gateentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gateentry',
            options={'verbose_name_plural': 'Gate Entry'},
        ),
        migrations.AlterModelOptions(
            name='offloadingbay',
            options={'verbose_name_plural': 'Offloading Bay'},
        ),
        migrations.AlterModelOptions(
            name='qualitycontrol',
            options={'verbose_name_plural': 'Quality Control'},
        ),
        migrations.AlterModelOptions(
            name='weighbridgein',
            options={'verbose_name_plural': 'Weigh Bridge In'},
        ),
        migrations.AlterModelOptions(
            name='weighbridgeout',
            options={'verbose_name_plural': 'Weigh Bridge Out'},
        ),
    ]
