# Generated by Django 4.2.9 on 2024-01-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_gateentry_options_alter_offloadingbay_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=50)),
                ('cab_plate', models.CharField(max_length=50)),
                ('trailer_plate', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='offloadingbay',
            options={'verbose_name_plural': 'Tank Farm'},
        ),
    ]
