# Generated by Django 4.2.9 on 2024-01-31 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_truck_alter_offloadingbay_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gateentry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='offloadingbay',
            options={},
        ),
        migrations.AlterModelOptions(
            name='qualitycontrol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weighbridgein',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weighbridgeout',
            options={},
        ),
        migrations.AddField(
            model_name='gateentry',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate', to='backend.truck'),
        ),
        migrations.AddField(
            model_name='offloadingbay',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offloadingbay', to='backend.truck'),
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualitycontrol', to='backend.truck'),
        ),
        migrations.AddField(
            model_name='weighbridgein',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weighbridgein', to='backend.truck'),
        ),
        migrations.AddField(
            model_name='weighbridgeout',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weighbridgeout', to='backend.truck'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='cab_plate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='truck',
            name='trailer_plate',
            field=models.CharField(max_length=20),
        ),
    ]
