# Generated by Django 4.2.9 on 2024-01-31 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_gateentry_options_alter_offloadingbay_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateentry',
            name='cleanliness',
        ),
        migrations.RemoveField(
            model_name='gateentry',
            name='leakages',
        ),
        migrations.RemoveField(
            model_name='gateentry',
            name='truck_registration',
        ),
        migrations.RemoveField(
            model_name='offloadingbay',
            name='truck_registration',
        ),
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='truck_registration',
        ),
        migrations.RemoveField(
            model_name='weighbridgein',
            name='truck_registration',
        ),
        migrations.RemoveField(
            model_name='weighbridgeout',
            name='truck_registration',
        ),
    ]
