# Generated by Django 4.2.9 on 2024-01-31 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_gateentry_cleanliness_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GateEntry',
            new_name='GeneralInfo',
        ),
    ]
