# Generated by Django 4.2.9 on 2024-01-31 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_gateentry_generalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general', to='backend.truck'),
        ),
    ]
