# Generated by Django 4.2.9 on 2024-02-01 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_generalinfo_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinfo',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='offloadingbay',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='weighbridgein',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='weighbridgeout',
            name='truck',
        ),
        migrations.AddField(
            model_name='truck',
            name='general_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='backend.generalinfo'),
        ),
        migrations.AddField(
            model_name='truck',
            name='quality_control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='backend.qualitycontrol'),
        ),
        migrations.AddField(
            model_name='truck',
            name='tankfarm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='backend.offloadingbay'),
        ),
        migrations.AddField(
            model_name='truck',
            name='weighbridge_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='backend.weighbridgein'),
        ),
        migrations.AddField(
            model_name='truck',
            name='weighbridge_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='backend.weighbridgeout'),
        ),
    ]
