# Generated by Django 4.2.9 on 2024-02-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_generalinfo_truck_remove_offloadingbay_truck_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalinfo',
            options={'verbose_name_plural': 'General Info (Gate)'},
        ),
        migrations.AlterModelOptions(
            name='offloadingbay',
            options={'verbose_name_plural': 'Tankfarm'},
        ),
        migrations.AlterModelOptions(
            name='qualitycontrol',
            options={'verbose_name_plural': 'Quality Control'},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'verbose_name_plural': 'All trucks'},
        ),
        migrations.AlterModelOptions(
            name='weighbridgein',
            options={'verbose_name_plural': 'Weighbridge-in'},
        ),
        migrations.AlterModelOptions(
            name='weighbridgeout',
            options={'verbose_name_plural': 'Weighbridge-out'},
        ),
    ]
