# Generated by Django 4.2.10 on 2024-02-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_generalinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='driver',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='truck',
            name='general_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='backend.generalinfo'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='quality_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='backend.qualitycontrol'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='tankfarm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='backend.offloadingbay'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='weighbridge_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='backend.weighbridgein'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='weighbridge_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='backend.weighbridgeout'),
        ),
    ]
